DROP TABLE IF EXISTS cities;

create table cities (
  id SERIAL PRIMARY KEY,
	city VARCHAR(50),
	state VARCHAR(50),
	population INT,
	mayor VARCHAR(50)
);

insert into cities (city, state, population, mayor) values ('Baton Rouge', 'LA', 469262636, 'Pavlov Pirkis');
insert into cities (city, state, population, mayor) values ('Irvine', 'CA', 196452402, 'Nevin Yele');
insert into cities (city, state, population, mayor) values ('Sioux Falls', 'SD', 91336058, 'Annie Fussie');
insert into cities (city, state, population, mayor) values ('Birmingham', 'AL', 188539518, 'Rafael Tumelty');
insert into cities (city, state, population, mayor) values ('Raleigh', 'NC', 415886880, 'Berke Carsey');
insert into cities (city, state, population, mayor) values ('Fresno', 'CA', 333943484, 'Lorry Howsan');
insert into cities (city, state, population, mayor) values ('Albany', 'NY', 322279172, 'Kevon Whaites');
insert into cities (city, state, population, mayor) values ('Jacksonville', 'FL', 375009360, 'Bethina Colyer');
insert into cities (city, state, population, mayor) values ('Greeley', 'CO', 323199439, 'Annemarie McWilliam');
insert into cities (city, state, population, mayor) values ('Indianapolis', 'IN', 488761715, 'Kent Negus');
insert into cities (city, state, population, mayor) values ('Charleston', 'WV', 338692742, 'Blakelee Worsam');
insert into cities (city, state, population, mayor) values ('Clearwater', 'FL', 459365931, 'Jarrod Biggadyke');
insert into cities (city, state, population, mayor) values ('Chico', 'CA', 395816157, 'Ferne Gamlin');
insert into cities (city, state, population, mayor) values ('Dallas', 'TX', 261308883, 'Jemie Scripps');
insert into cities (city, state, population, mayor) values ('Savannah', 'GA', 456667375, 'Maxim Dommett');
insert into cities (city, state, population, mayor) values ('Syracuse', 'NY', 153634321, 'Arny Shimuk');
insert into cities (city, state, population, mayor) values ('Gainesville', 'GA', 254901704, 'Carroll Avrahamian');
insert into cities (city, state, population, mayor) values ('Ogden', 'UT', 101746292, 'Livia Bastable');
insert into cities (city, state, population, mayor) values ('Wichita', 'KS', 300228642, 'Annabela Reap');
insert into cities (city, state, population, mayor) values ('Washington', 'DC', 332853389, 'Damara Ogger');
insert into cities (city, state, population, mayor) values ('Honolulu', 'HI', 185368053, 'Shaun Reppaport');
insert into cities (city, state, population, mayor) values ('Suffolk', 'VA', 34170882, 'Kaleena Farfolomeev');
insert into cities (city, state, population, mayor) values ('Toledo', 'OH', 436980828, 'Norina Perview');
insert into cities (city, state, population, mayor) values ('Charleston', 'SC', 305478034, 'Kerrin Dionisii');
insert into cities (city, state, population, mayor) values ('Salt Lake City', 'UT', 311588230, 'Erinn Marlen');
insert into cities (city, state, population, mayor) values ('Ocala', 'FL', 206599970, 'Leanna Brayley');
insert into cities (city, state, population, mayor) values ('Alexandria', 'LA', 277142363, 'Mitzi Donner');
insert into cities (city, state, population, mayor) values ('Tampa', 'FL', 457817660, 'Inessa Zanni');
insert into cities (city, state, population, mayor) values ('Raleigh', 'NC', 477763434, 'Matteo Huddle');
insert into cities (city, state, population, mayor) values ('Baton Rouge', 'LA', 470478468, 'Tiphanie Ciottoi');
insert into cities (city, state, population, mayor) values ('New York City', 'NY', 160259747, 'Jen Lory');
insert into cities (city, state, population, mayor) values ('New Haven', 'CT', 242862882, 'Hayden Mahmood');
insert into cities (city, state, population, mayor) values ('Brea', 'CA', 121526419, 'Lin Sapsford');
insert into cities (city, state, population, mayor) values ('Phoenix', 'AZ', 277924386, 'Kimble Lindhe');
insert into cities (city, state, population, mayor) values ('Lansing', 'MI', 95250911, 'Romonda Grinin');
insert into cities (city, state, population, mayor) values ('Dallas', 'TX', 377311157, 'Rafaello Rowe');
insert into cities (city, state, population, mayor) values ('Houston', 'TX', 96578832, 'Merline Wasiel');
insert into cities (city, state, population, mayor) values ('Corpus Christi', 'TX', 95847144, 'Seka Adame');
insert into cities (city, state, population, mayor) values ('Stamford', 'CT', 411042355, 'Sidonnie Vaillant');
insert into cities (city, state, population, mayor) values ('San Antonio', 'TX', 394003263, 'La verne Ervin');
insert into cities (city, state, population, mayor) values ('Washington', 'DC', 197623854, 'Nelli Dunbleton');
insert into cities (city, state, population, mayor) values ('Valdosta', 'GA', 326021628, 'Chastity Corradengo');
insert into cities (city, state, population, mayor) values ('Corpus Christi', 'TX', 101065975, 'Tatiana Milesop');
insert into cities (city, state, population, mayor) values ('Charlotte', 'NC', 141802790, 'Dulcie Goodlet');
insert into cities (city, state, population, mayor) values ('Pensacola', 'FL', 331879777, 'Ernst Exelby');
insert into cities (city, state, population, mayor) values ('Orlando', 'FL', 465405792, 'Philomena Bedward');
insert into cities (city, state, population, mayor) values ('Muncie', 'IN', 361932871, 'Leodora Pariss');
insert into cities (city, state, population, mayor) values ('Anaheim', 'CA', 431001079, 'Freddy Joly');
insert into cities (city, state, population, mayor) values ('Columbia', 'SC', 495592119, 'Cynthia Shillito');
insert into cities (city, state, population, mayor) values ('Hampton', 'VA', 161968574, 'Gladi Seabrocke');
insert into cities (city, state, population, mayor) values ('Saint Petersburg', 'FL', 18951260, 'Anatola Barbosa');
insert into cities (city, state, population, mayor) values ('Pueblo', 'CO', 276407507, 'Siobhan Riddlesden');
insert into cities (city, state, population, mayor) values ('Chico', 'CA', 104905658, 'Jilli Point');
insert into cities (city, state, population, mayor) values ('New York City', 'NY', 353062072, 'Elihu Renvoys');
insert into cities (city, state, population, mayor) values ('Winston Salem', 'NC', 4015380, 'Sissie Westall');
insert into cities (city, state, population, mayor) values ('Baltimore', 'MD', 497806216, 'Marley Rival');
insert into cities (city, state, population, mayor) values ('San Antonio', 'TX', 302574387, 'Shawn Summers');
insert into cities (city, state, population, mayor) values ('Brooklyn', 'NY', 105779633, 'Vladamir Pape');
insert into cities (city, state, population, mayor) values ('Raleigh', 'NC', 318017940, 'Wren Aikett');
insert into cities (city, state, population, mayor) values ('San Jose', 'CA', 122830743, 'Rickard Roome');
insert into cities (city, state, population, mayor) values ('Odessa', 'TX', 145874981, 'Marve Ogger');
insert into cities (city, state, population, mayor) values ('San Antonio', 'TX', 30705033, 'Evelina Seago');
insert into cities (city, state, population, mayor) values ('Worcester', 'MA', 34862245, 'Cahra Dimelow');
insert into cities (city, state, population, mayor) values ('Phoenix', 'AZ', 243465905, 'Bondie Nowlan');
insert into cities (city, state, population, mayor) values ('Minneapolis', 'MN', 374444418, 'Karlotta Camplin');
insert into cities (city, state, population, mayor) values ('Corpus Christi', 'TX', 18410826, 'Hestia Flade');
insert into cities (city, state, population, mayor) values ('Columbus', 'OH', 18992819, 'Terza Konzelmann');
insert into cities (city, state, population, mayor) values ('Buffalo', 'NY', 163188482, 'Fredra Rushmer');
insert into cities (city, state, population, mayor) values ('San Antonio', 'TX', 402674146, 'Desirae Harmant');
insert into cities (city, state, population, mayor) values ('New York City', 'NY', 312861697, 'Berne Dulinty');
insert into cities (city, state, population, mayor) values ('Albuquerque', 'NM', 147596785, 'Rita McCluskey');
insert into cities (city, state, population, mayor) values ('Minneapolis', 'MN', 338456086, 'Mil Ilott');
insert into cities (city, state, population, mayor) values ('Pittsburgh', 'PA', 338599083, 'Elyssa Petru');
insert into cities (city, state, population, mayor) values ('Charlotte', 'NC', 424781093, 'Putnam Bales');
insert into cities (city, state, population, mayor) values ('Honolulu', 'HI', 412318246, 'Orelia Tingley');
insert into cities (city, state, population, mayor) values ('Washington', 'DC', 264979784, 'Mariann Killough');
insert into cities (city, state, population, mayor) values ('New York City', 'NY', 494933392, 'Job Morton');
insert into cities (city, state, population, mayor) values ('Hialeah', 'FL', 419036530, 'Leontine Tack');
insert into cities (city, state, population, mayor) values ('Fort Worth', 'TX', 270415336, 'Giusto Power');
insert into cities (city, state, population, mayor) values ('West Palm Beach', 'FL', 340251795, 'Roxanne Kinchley');
insert into cities (city, state, population, mayor) values ('Wichita Falls', 'TX', 385039883, 'Jan Banane');
insert into cities (city, state, population, mayor) values ('Montgomery', 'AL', 377612610, 'Stanislaw Uc');
insert into cities (city, state, population, mayor) values ('Bronx', 'NY', 161061493, 'Herminia Swaddle');
insert into cities (city, state, population, mayor) values ('Newark', 'DE', 237578883, 'Kelila Jesson');
insert into cities (city, state, population, mayor) values ('Atlanta', 'GA', 315196357, 'Devland Kleis');
insert into cities (city, state, population, mayor) values ('Houston', 'TX', 427134325, 'Evelyn Philson');
insert into cities (city, state, population, mayor) values ('Houston', 'TX', 289843765, 'Burl Rosbottom');
insert into cities (city, state, population, mayor) values ('Dallas', 'TX', 176687902, 'Frannie Sloam');
insert into cities (city, state, population, mayor) values ('Columbus', 'OH', 494967095, 'Hurlee Mewe');
insert into cities (city, state, population, mayor) values ('New Haven', 'CT', 333404432, 'Ashli Swannell');
insert into cities (city, state, population, mayor) values ('Houston', 'TX', 78658023, 'Reg Rusk');
insert into cities (city, state, population, mayor) values ('Denver', 'CO', 453003030, 'Rudy Summerskill');
insert into cities (city, state, population, mayor) values ('Monroe', 'LA', 273261203, 'Archibaldo Dancy');
insert into cities (city, state, population, mayor) values ('Roanoke', 'VA', 297466983, 'Wendall Manktelow');
insert into cities (city, state, population, mayor) values ('Tucson', 'AZ', 423208328, 'Elspeth Muge');
insert into cities (city, state, population, mayor) values ('Detroit', 'MI', 90149661, 'Ker Raubenheimers');
insert into cities (city, state, population, mayor) values ('Orlando', 'FL', 155477805, 'Imojean Deverill');
insert into cities (city, state, population, mayor) values ('Burbank', 'CA', 32310532, 'Eydie Saunt');
insert into cities (city, state, population, mayor) values ('New Orleans', 'LA', 140831581, 'Alexis Boram');
insert into cities (city, state, population, mayor) values ('Birmingham', 'AL', 64117072, 'Colet Warrington');
